language: go

go:
  - 1.0
  - 1.1
  - tip

env:
  global:
    #- secure: "G9JEcJCHpKmDCZRTGqqgEKHYrwWGJu14Lf3mMeCTyYmvjVwUVRhgs36trQTit0aRKmggv2yiwGDp01iCDb0J4C+YAsqSMLP2gWoCRV2pPowCRNtoJOQ4KX0qkFUj3Qdv8Qlrc8P/cYzPYAQ0xNL0uJldF5Ak9aFShV3nEy/M/XY="
    #- secure: "jg3OsYR9BZohxRFwAuXV5jTmBX7FAWKpGe+LvAfyQPAN5WmEDIiHaHsyrykH8hg4GP5MpENv01kZNaB/WKP0CsKAmu0axJLc2cWtniBRq5yozCCbhRF57wFaA+ZUDALDJdmCzZVFQxilDlu8TKKgVh/Tm03I1QEMgaGRt/gFX6I="
    - secure: "tBqM1SVcEHaHGwMBBwkAaDGZ6QnQB4Pnse9TZK6xYCM96WFzHVImVCo1DTWCMlw3qZwbD7OfB3IGfP4uzEJPrNhSyzKCg4cB4CT+o5IaiBuP2KEqBptsWySvt4TzRNqvbn+5UM2JpmGMrje30c1x0EvaoN+nQnjwvIRFMtcEurQ="
    - secure: "RtTVFFN2EkDyAvbbpVK3DfravsvfxGZwf6Rh7CMQ2yNCZkdrfSxuPPRO2gybqR8T9Y0KJ3ibvTg6AAyCmHM682qymRZeA9xaRSV6eSaPP7E6tCKvOuG1asfpVYZIaS2ULNc7L9R36DYxq66CVcTCL/RRqFeHc5W42zE3t9kir4A="

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install git mercurial
 

install:
 - cd server
 - cp .config.go.travis config.go
 - echo $CLIENT_ID >> config.go
 - echo $CLIENT_SECRET >> config.go
 - cat config.go
 - bash install.sh

script: