language: go

go:
  - 1.1

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install golang git mercurial redis-server
 

install:
 - cd server && cp .config.go.travis config.go && sudo bash install.sh